#!/usr/bin/env bash
#
# FILE: /opt/local/scripts/rc/bash/701_exports.conf
########
#
# PATH
export PATH="/usr/lib/icecc:${PATH}"

# PORTAGE
export EIX_LIMIT=0



#
# END FILE : /opt/local/scripts/rc/bash/701_exports.conf
################################################################################
